# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dokku Blog
# email: dokku@example.com
description: > # this means to ignore newlines until "baseurl:"
  The Official Blog for Dokku, a docker-powered PaaS that helps you
  build and manage the lifecycle of applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dokku.github.io" # the base hostname & protocol for your site
# twitter_username: dokku
# github_username:  dokku

# Build settings
markdown: kramdown

permalink: /:categories/:title
